android/Bottari/presentation/src/main/java/com/bottari/presentation/base/BaseActivity.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/base/BaseFragment.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/base/UiState.kt
- 공통 로직 추상화
<br>
closed #21 
<br>
- BaseActivity 작성
- BaseFragment 작성
- UI 상태 정의
<br>
- SingleLiveData 추후 반영
- BaseViewModel 고려
<br>
=> [AN] Presentation Base 코드 작성

backend/bottari/src/main/java/com/bottari/controller/BottariItemController.java, backend/bottari/src/main/java/com/bottari/dto/ReadBottariItemResponse.java, backend/bottari/src/main/java/com/bottari/repository/BottariItemRepository.java, backend/bottari/src/main/java/com/bottari/service/BottariItemService.java, backend/bottari/src/test/java/com/bottari/controller/BottariItemControllerTest.java, backend/bottari/src/test/java/com/bottari/service/BottariItemServiceTest.java
- 보따리 체크리스트 조회 기능 구현
<br>
Closed #25 
<br>
- 체크리스트 조회 기능 구현 및 테스트 작성
<br>
4인 페어 진행
<br>
=> [BE] 보따리 체크리스트 조회 기능 구현

.github/workflows/auto-close-issues-on-pr-merge.yaml
- PR Close시 자동으로 이슈를 닫기 위해서 workflow를 추가하였습니다.
<br>
Closed #28 
<br>
```yaml
name: Auto Close Issues on PR Merge
on:
pull_request:
types: [closed]
jobs:
close-referenced-issues:
if: github.event.pull_request.merged == true
runs-on: ubuntu-latest
permissions:
issues: write
contents: read
steps:
- name: Close issues mentioned in PR body
uses: actions/github-script@v7
with:
github-token: ${{ secrets.GITHUB_TOKEN }}
script: |
const pr = context.payload.pull_request;
const body = pr.body || "";
const owner = context.repo.owner;
const repo = context.repo.repo;
const matches = [...body.matchAll(/(?:Fixes|Closes|Resolves|Closed)\s+#(\d+)/gi)];
if (matches.length === 0) {
console.log("No issues referenced for closure.");
return;
}
for (const match of matches) {
const issue_number = match[1]; …
```
=> [ALL] 모든 브랜치 PR 병합 시 관련 이슈 자동 닫기 기능 구현

android/Bottari/gradle/libs.versions.toml, android/Bottari/presentation/build.gradle.kts, android/Bottari/presentation/src/main/java/com/bottari/presentation/base/BaseActivity.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/extension/DateTimeExtension.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/extension/ViewExtension.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/model/AlarmTypeUiModel.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/model/BottariUiModel.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/home/HomeActivity.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/home/bottari/BottariFragment.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/home/bottari/BottariViewModel.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/home/bottari/adapter/BottariAdapter.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/home/bottari/adapter/BottariViewHolder.kt, android/Bottari/presentation/src/main/res/drawable/bg_black_radius_12dp.xml, android/Bottari/presentation/src/main/res/drawable/bg_primary_oval.xml, android/Bottari/presentation/src/main/res/drawable/bg_progress_bottari.xml, android/Bottari/presentation/src/main/res/layout/activity_home.xml, android/Bottari/presentation/src/main/res/layout/fragment_bottari.xml, android/Bottari/presentation/src/main/res/layout/item_bottari.xml, android/Bottari/presentation/src/main/res/values/font_style.xml, android/Bottari/presentation/src/main/res/values/strings.xml
- 나의 보따리 화면 (메인 화면) 구현
<br>
Closed #24 
<br>
- 보따리 목록 출력
- 보따리 정보 출력 (체크 완료한 물건 개수, 전체 물건 개수, 알람 정보)
- 보따리 생성 버튼 추가
- 스크롤 시 버튼 페이드 인/아웃 애니메이션 구현
- 시스템 바 영역 SDK 버전별 분기 처리
<br>
https://github.com/user-attachments/assets/adf331b9-c143-4f69-a877-f047011669ed
<br>
- 보따리 버튼 클릭 시 생성 기능 구현 필요
- 보따리 항목 클릭 시 체크리스트 구현 필요
- 보따리 항목 메뉴 구현 필요
<br>
=> [AN] 나의 보따리 화면 구현

backend/bottari/src/main/java/com/bottari/controller/BottariController.java, backend/bottari/src/main/java/com/bottari/domain/Bottari.java, backend/bottari/src/main/java/com/bottari/dto/AlarmResponse.java, backend/bottari/src/main/java/com/bottari/dto/ReadBottariPreviewResponse.java, backend/bottari/src/main/java/com/bottari/dto/ReadBottariResponse.java, backend/bottari/src/main/java/com/bottari/repository/AlarmRepository.java, backend/bottari/src/main/java/com/bottari/repository/BottariItemRepository.java, backend/bottari/src/main/java/com/bottari/repository/BottariRepository.java, backend/bottari/src/main/java/com/bottari/service/BottariService.java, backend/bottari/src/test/java/com/bottari/controller/BottariControllerTest.java, backend/bottari/src/test/java/com/bottari/service/BottariServiceTest.java
- 내 보따리 목록 조회 API 구현
<br>
- Closed #4 
<br>
- 내 보따리 목록 조회 API 구현
- 내 보따리 목록 조회 테스트 작성
<br>
- 4인 페어 진행
<br>
=> [BE] 내 보따리 목록 조회 기능 구현

.github/workflows/deploy-dev-server.yml
- 배포 자동화 파이프라인 구축
<br>
- Closed #52 
<br>
- GitHub Actions, Self-Hosted-Runner 사용
<br>
- 4인 페어 진행
<br>
=> [BE] 배포 자동화 파이프라인 구축

android/Bottari/gradle/libs.versions.toml, android/Bottari/presentation/build.gradle.kts, android/Bottari/presentation/src/main/java/com/bottari/presentation/common/ItemSpacingDecoration.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/model/AlarmType.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/model/AlarmUiModel.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/model/DayOfWeekUiModel.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/alarm/AlarmEditFragment.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/alarm/AlarmEditViewModel.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/alarm/adapter/DayOfWeekAdapter.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/alarm/adapter/DayOfWeekViewHolder.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/alarm/listener/OnDayOfWeekClickListener.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/personal/main/PersonalBottariEditFragment.kt, android/Bottari/presentation/src/main/res/drawable/bg_gray_oval.xml, android/Bottari/presentation/src/main/res/drawable/bg_white_radius_12dp_gray_stroke.xml, android/Bottari/presentation/src/main/res/drawable/btn_location.xml, android/Bottari/presentation/src/main/res/layout/fragment_alarm_edit.xml, android/Bottari/presentation/src/main/res/layout/fragment_personal_bottari_edit.xml, android/Bottari/presentation/src/main/res/layout/item_day_of_week.xml, android/Bottari/presentation/src/main/res/layout/layout_alarm_edit_time_picker.xml, android/Bottari/presentation/src/main/res/values/colors.xml, android/Bottari/presentation/src/main/res/values/dimens.xml, android/Bottari/presentation/src/main/res/values/strings.xml, android/Bottari/presentation/src/main/res/values/styles.xml
- 알람 설정 화면 구현
<br>
- Closed #38 
<br>
- `NumberPicker`를 이용한 알람 날짜 및 시간 선택 기능 구현
- 알람 유형 별로 다른 정보 선택
<br>
https://github.com/user-attachments/assets/53325e66-4b19-42fc-adc6-1512cd47c13b
<br>
- 추후 서버 연동 구현
- 화면 전환 애니메이션 고려
- `NumberPicker` 스타일 추가 고려
<br>
=> [AN] 알람 설정 화면 구현

backend/bottari/src/main/java/com/bottari/BottariApplication.java, backend/bottari/src/main/java/com/bottari/config/JpaAuditingConfig.java, backend/bottari/src/main/java/com/bottari/controller/BottariTemplateController.java, backend/bottari/src/main/java/com/bottari/controller/docs/BottariTemplateApiDocs.java, backend/bottari/src/main/java/com/bottari/domain/BottariTemplate.java, backend/bottari/src/main/java/com/bottari/dto/ReadBottariTemplateResponse.java, backend/bottari/src/main/java/com/bottari/repository/BottariTemplateItemRepository.java, backend/bottari/src/main/java/com/bottari/repository/BottariTemplateRepository.java, backend/bottari/src/main/java/com/bottari/service/BottariTemplateService.java, backend/bottari/src/test/java/com/bottari/controller/BottariTemplateControllerTest.java, backend/bottari/src/test/java/com/bottari/service/BottariTemplateServiceTest.java
- 보따리 템플릿 상세 조회 기능 
- 모든 템플릿 조회 및 검색 기능 구현
<br>
- Closed #62 
- Closed #63 
<br>
- 보따리 템플릿 상세 조회 기능 구현
- 보따리 템플릿 목록 조회 기능 구현
- 검색 기능 구현
- 검색어가 없을 시, 전체 목록 조회
- 최신순 정렬
<br>
- 벨로 & 훌라 2인 페어 진행
- #66  머지 후 작업
<br>
=> [BE] 보따리 템플릿 조회 기능 구현

backend/bottari/src/main/java/com/bottari/domain/RoutineAlarm.java, backend/bottari/src/main/resources/application.yml, backend/bottari/src/main/resources/data.sql, backend/bottari/src/test/resources/application.yml
- 개발 서버 DB 더미 데이터 추가
<br>
- Closed #86 
<br>
- 클라이언트 테스트용 더미데이터 data.sql 작성
<br>
<br>
=> [BE] 개발 서버 DB 더미 데이터 추가

backend/bottari/src/main/java/com/bottari/dto/AlarmResponse.java, backend/bottari/src/test/java/com/bottari/service/BottariServiceTest.java
- 보따리 상세조회 및 목록 조회 시 알람 활성화 여부가 응답되지 않는 문제 수정
<br>
- Closed #89 
<br>
- 보따리 상세조회 시, 알람 활성화 여부 응답
- 보따리 목록 조회 시, 알람 활성화 여부 응답
- 변경 사항 대응 테스트 코드 작성
<br>
<br>
=> [BE] 보따리 상세조회 및 목록 조회 시 알람 활성화 여부가 응답되지 않는 문제 수정

android/Bottari/data/src/main/java/com/bottari/data/mapper/BottariItemMapper.kt, android/Bottari/data/src/main/java/com/bottari/data/model/item/FetchChecklistResponse.kt, android/Bottari/data/src/main/java/com/bottari/data/repository/BottariItemRepositoryImpl.kt, android/Bottari/data/src/main/java/com/bottari/data/service/BottariItemService.kt, android/Bottari/data/src/main/java/com/bottari/data/source/remote/BottariItemRemoteDataSource.kt, android/Bottari/data/src/main/java/com/bottari/data/source/remote/BottariItemRemoteDataSourceImpl.kt, android/Bottari/di/src/main/java/com/bottari/di/DataSourceProvider.kt, android/Bottari/di/src/main/java/com/bottari/di/RepositoryProvider.kt, android/Bottari/di/src/main/java/com/bottari/di/ServiceProvider.kt, android/Bottari/di/src/main/java/com/bottari/di/UseCaseProvider.kt, android/Bottari/domain/src/main/java/com/bottari/domain/repository/BottariItemRepository.kt, android/Bottari/domain/src/main/java/com/bottari/domain/usecase/item/CheckBottariItemUseCase.kt, android/Bottari/domain/src/main/java/com/bottari/domain/usecase/item/FetchChecklistUseCase.kt, android/Bottari/domain/src/main/java/com/bottari/domain/usecase/item/UnCheckBottariItemUseCase.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/mapper/BottariMapper.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/checklist/ChecklistActivity.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/checklist/ChecklistViewModel.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/checklist/main/MainChecklistFragment.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/checklist/swipe/SwipeChecklistFragment.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/home/bottari/BottariFragment.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/home/bottari/adapter/BottariViewHolder.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/home/bottari/listener/OnBottariClickListener.kt
- 체크리스트 화면 API 연동 및 화면 전환 로직 개선
<br>
- Closed #94
<br>
- `mutableMap`과 `Job`을 활용한 API 호출 관리
- 함수를 마지막으로 호출한 후 일정 시간이 경과한 후에만 함수가 실행되도록 처리함 (디바운스)
- 중복 코드 제거
- 복잡한 화면 전환 로직 개선
<br>
=> [AN] 체크리스트 화면 API 연동 및 화면 전환 로직 개선

android/Bottari/data/src/main/java/com/bottari/data/mapper/BottariTemplateMapper.kt, android/Bottari/data/src/main/java/com/bottari/data/model/template/BottariTemplateItemResponse.kt, android/Bottari/data/src/main/java/com/bottari/data/model/template/FetchBottariTemplateResponse.kt, android/Bottari/data/src/main/java/com/bottari/data/repository/BottariTemplateRepositoryImpl.kt, android/Bottari/data/src/main/java/com/bottari/data/service/BottariTemplateService.kt, android/Bottari/data/src/main/java/com/bottari/data/source/remote/BottariTemplateRemoteDataSource.kt, android/Bottari/data/src/main/java/com/bottari/data/source/remote/BottariTemplateRemoteDataSourceImpl.kt, android/Bottari/di/src/main/java/com/bottari/di/DataSourceProvider.kt, android/Bottari/di/src/main/java/com/bottari/di/RepositoryProvider.kt, android/Bottari/di/src/main/java/com/bottari/di/ServiceProvider.kt, android/Bottari/di/src/main/java/com/bottari/di/UseCaseProvider.kt, android/Bottari/domain/src/main/java/com/bottari/domain/model/template/BottariTemplate.kt, android/Bottari/domain/src/main/java/com/bottari/domain/model/template/BottariTemplateItem.kt, android/Bottari/domain/src/main/java/com/bottari/domain/repository/BottariTemplateRepository.kt, android/Bottari/domain/src/main/java/com/bottari/domain/usecase/template/FetchBottariTemplatesUseCase.kt, android/Bottari/domain/src/main/java/com/bottari/domain/usecase/template/SearchBottariTemplatesUseCase.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/mapper/BottariTemplateMapper.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/model/BottariTemplateItemUiModel.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/model/BottariTemplateUiModel.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/util/Debounce.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/home/market/MarketFragment.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/home/market/MarketViewModel.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/home/market/adapter/MarketAdapter.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/home/market/adapter/MarketViewHolder.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/home/market/listener/OnBottariTemplateClickListener.kt, android/Bottari/presentation/src/main/res/drawable/bg_gray_radius_20dp.xml, android/Bottari/presentation/src/main/res/layout/fragment_market.xml, android/Bottari/presentation/src/main/res/layout/item_bottari_template.xml, android/Bottari/presentation/src/main/res/values/strings.xml
- 마켓플레이스 화면 구현
<br>
- Closed #41 
<br>
- 마켓 화면 UI 구현
- 템플릿 목록 조회 API 연동
- 템플릿 검색 기능 구현
<br>
https://github.com/user-attachments/assets/58bdcd22-7d20-4034-a8ba-371f09199079
<br>
- 템플릿 클릭 시 처리 필요
- EditText 커서 색상 개선 필요
- 메뉴 클릭 시 처리 필요
<br>
=> [AN] 마켓플레이스 화면 구현

android/Bottari/presentation/build.gradle.kts, android/Bottari/presentation/src/main/AndroidManifest.xml, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/checklist/ChecklistActivity.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/home/HomeActivity.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/setting/SettingActivity.kt, android/Bottari/presentation/src/main/res/layout/activity_home.xml, android/Bottari/presentation/src/main/res/layout/activity_setting.xml, android/Bottari/presentation/src/main/res/values/strings.xml
- 설정 화면 구현
<br>
- Closed #97 
<br>
- 개인정보 처리 방침 (노션) 외부 브라우저 실행
<br>
[개인정보 처리 방침 (노션)](https://pine-amethyst-317.notion.site/238796fb6f228097ac22eafcc8dec207)
<br>
=> [AN] 설정 화면 구현

android/Bottari/data/src/main/java/com/bottari/data/model/template/CreateBottariTemplateRequest.kt, android/Bottari/data/src/main/java/com/bottari/data/repository/BottariRepositoryImpl.kt, android/Bottari/data/src/main/java/com/bottari/data/repository/BottariTemplateRepositoryImpl.kt, android/Bottari/data/src/main/java/com/bottari/data/service/BottariTemplateService.kt, android/Bottari/data/src/main/java/com/bottari/data/source/remote/BottariRemoteDataSource.kt, android/Bottari/data/src/main/java/com/bottari/data/source/remote/BottariRemoteDataSourceImpl.kt, android/Bottari/data/src/main/java/com/bottari/data/source/remote/BottariTemplateRemoteDataSource.kt, android/Bottari/data/src/main/java/com/bottari/data/source/remote/BottariTemplateRemoteDataSourceImpl.kt, android/Bottari/di/src/main/java/com/bottari/di/UseCaseProvider.kt, android/Bottari/domain/src/main/java/com/bottari/domain/repository/BottariRepository.kt, android/Bottari/domain/src/main/java/com/bottari/domain/repository/BottariTemplateRepository.kt, android/Bottari/domain/src/main/java/com/bottari/domain/usecase/bottari/CreateBottariUseCase.kt, android/Bottari/domain/src/main/java/com/bottari/domain/usecase/template/CreateBottariTemplateUseCase.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/personal/main/PersonalBottariEditFragment.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/personal/main/PersonalBottariEditViewModel.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/home/bottari/create/BottariCreateDialog.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/home/bottari/create/BottariCreateViewModel.kt, android/Bottari/presentation/src/main/res/layout/fragment_market.xml, android/Bottari/presentation/src/main/res/menu/personal_bottari_edit_popup_menu.xml, android/Bottari/presentation/src/main/res/values/strings.xml, android/Bottari/presentation/src/main/res/values/styles.xml
- 내 보따리에서 마켓 등록 기능을 구현한다.
<br>
- Closed #109
<br>
- 내 보따리에서 Popup Menu을 통해 마켓 등록하기 기능을 구현한다.
<br>
<br>
=> [AN] 내 보따리 마켓 등록 기능 구현

android/Bottari/presentation/src/main/java/com/bottari/presentation/base/BaseActivity.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/base/BaseFragment.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/personal/item/PersonalItemEditFragment.kt
- 시스템 네비게이션 하단 패딩 문제 해결
<br>
- Closed #120
<br>
- 시스템 네비게이션 하단 패딩 문제 해결
- `ViewCompat.setOnApplyWindowInsetsListener` 사용하여 현재 환경에 맞게 패딩 수정되도록 개선
<br>
<br>
=> [AN] 시스템 네비게이션 하단 패딩 문제 해결

android/Bottari/app/src/main/res/values-night/themes.xml, android/Bottari/app/src/main/res/values/themes.xml, android/Bottari/presentation/src/main/java/com/bottari/presentation/base/BaseActivity.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/home/bottari/BottariFragment.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/home/bottari/create/BottariCreateDialog.kt, android/Bottari/presentation/src/main/res/layout/fragment_bottari.xml, android/Bottari/presentation/src/main/res/layout/item_bottari.xml, android/Bottari/presentation/src/main/res/layout/item_bottari_template.xml, android/Bottari/presentation/src/main/res/layout/item_checklist.xml, android/Bottari/presentation/src/main/res/layout/item_edit_personal_item.xml, android/Bottari/presentation/src/main/res/layout/item_market_bottari_detail_item.xml
- 사이즈 불일치, 그림자 등 UI 개선
<br>
- Closed #122 
<br>
- 보따리 목록 화면에서 생성 버튼에 의해 보따리 편집 버튼이 가려지는 문제 해결
- RecyclerView 최상단의 그림자가 사라지는 문제 해결
- 보따리 생성 다이얼로그 배경 투명 처리
<br>
<br>
=> [AN] UI 개선

android/Bottari/presentation/src/main/java/com/bottari/presentation/common/BottomPaddingDecoration.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/home/bottari/BottariFragment.kt, android/Bottari/presentation/src/main/res/layout/fragment_bottari.xml
- RecyclerView 하단의 FadingEdge가 보이는 문제 해결
<br>
- Closed #131 
<br>
- 보따리 생성 버튼의 높이를 계산하여 여백 부여
<br>
<br>
=> [AN] RecycleView 하단의 FadingEdge가 보이는 문제

backend/bottari/src/main/java/com/bottari/service/BottariService.java, backend/bottari/src/test/java/com/bottari/service/BottariServiceTest.java
- 
<br>
- Closed 
<br>
-
<br>
| Before | After |
|--------|-------|
| (이전 화면) | (변경된 화면) |
<br>
<br>
=> [BE] 배포 파이프라인 테스트

backend/bottari/src/main/java/com/bottari/service/BottariService.java, backend/bottari/src/test/java/com/bottari/service/BottariServiceTest.java
- #133 시연을 위해 변경한 작업 롤백
<br>
- 시연 후 되돌립니다.
<br>
<br>
=> [BE] 배포 파이프라인 시연을 위한 작업 롤백

backend/bottari/src/main/java/com/bottari/controller/BottariTemplateController.java, backend/bottari/src/main/java/com/bottari/controller/docs/BottariTemplateApiDocs.java, backend/bottari/src/main/java/com/bottari/domain/BottariTemplate.java, backend/bottari/src/main/java/com/bottari/repository/BottariTemplateItemRepository.java, backend/bottari/src/main/java/com/bottari/service/BottariService.java, backend/bottari/src/main/java/com/bottari/service/BottariTemplateService.java, backend/bottari/src/test/java/com/bottari/controller/BottariTemplateControllerTest.java, backend/bottari/src/test/java/com/bottari/domain/BottariTemplateTest.java, backend/bottari/src/test/java/com/bottari/service/BottariItemServiceTest.java, backend/bottari/src/test/java/com/bottari/service/BottariTemplateServiceTest.java
- 내 보따리 템플릿 삭제 기능 추가
<br>
- Closed #148
<br>
- 내 보따리 템플릿 삭제 기능 추가
- 내 보따리 템플릿 삭제 API 추가
<br>
=> [BE] 내 보따리 템플릿 삭제 기능 구현

android/Bottari/data/src/main/java/com/bottari/data/repository/MemberRepositoryImpl.kt, android/Bottari/data/src/test/java/com/bottari/data/repository/MemberRepositoryImplTest.kt, android/Bottari/domain/src/main/java/com/bottari/domain/model/member/Member.kt, android/Bottari/domain/src/main/java/com/bottari/domain/repository/MemberRepository.kt, android/Bottari/domain/src/main/java/com/bottari/domain/usecase/member/RegisterMemberUseCase.kt
- 오류 해결
<br>
- Closed #172 
<br>
- 최초 등록 시 `MemberRepository`에 SSAID만을 전달하도록 변경
<br>
<br>
=> [AN] 최초 등록 시 Member 객체에서 예외가 발생하는 문제 해결

backend/bottari/src/main/java/com/bottari/controller/BottariController.java, backend/bottari/src/test/java/com/bottari/controller/BottariTemplateControllerTest.java, backend/bottari/src/test/java/com/bottari/domain/BottariTemplateTest.java, backend/bottari/src/test/java/com/bottari/service/AlarmServiceTest.java, backend/bottari/src/test/java/com/bottari/service/BottariItemServiceTest.java, backend/bottari/src/test/java/com/bottari/service/BottariServiceTest.java, backend/bottari/src/test/java/com/bottari/service/BottariTemplateServiceTest.java, backend/bottari/src/test/java/com/bottari/service/MemberServiceTest.java
- 테스트 케이스 `@Nested` 사용 그룹화
<br>
- Closed #76 
<br>
- 도메인, 컨트롤러 테스트는 메서드 당 테스트 갯수가 많지 않아 그다지 가독성이 떨어진다고 느끼지 못함.
- 따라서 비교적 메서드당 예외 테스트가 많은 서비스 테스트에만 적용함.
<br>
<br>
=> [BE] 테스트 케이스 @Nested 사용 그룹화

backend/bottari/src/main/java/com/bottari/dto/CheckRegistrationResponse.java, backend/bottari/src/main/java/com/bottari/service/MemberService.java, backend/bottari/src/test/java/com/bottari/controller/MemberControllerTest.java, backend/bottari/src/test/java/com/bottari/service/MemberServiceTest.java
- Android Crashlytics 작업에 필요한 사용자 고유 값(member ID) 전달
<br>
- Closed #214 
<br>
- id 필드 추가
=> [BE] 사용자 확인 API 응답에 memberId 필드 추가

android/Bottari/presentation/src/main/java/com/bottari/presentation/view/template/create/TemplateCreateUiState.kt
- 모두의 보따리 등록 시 빈 제목으로 요청하는 문제 수정
<br>
- Closed #238 
<br>
<br>
=> [AN] 모두의 보따리 등록 시 빈 제목으로 요청하는 문제 수정

.github/workflows/pr-notification.yml
- PR 디스코드 알람 시, 메시지 본문 커맨드 인식 오류
<br>
- Closed #259 
<br>
- PR 리뷰 코멘트에 `@AnyCommand` 형식으로 자바 어노테이션 작성 시,
Bash에서 이를 커맨드로 인식하고 디스코드 알람 과정에서 오류 발생
- 디스코드 알람 시, 리뷰 메시지 본문을 보내지 않도록 수정
<br>
<br>
=> [BE] PR 디스코드 알람 시, 메시지 본문 커맨드 인식 오류 수정

.github/workflows/deploy-dev-server.yml, backend/bottari/build.gradle, backend/bottari/src/main/resources/application-dev.yml, backend/demo/.idea/vcs.xml
- 개발 서버의 데이터 베이스르 mysql로 바꾼다.
<br>
- Closed #252 
<br>
- EC2에 Docker 설치
- EC2에 mysql-compose 파일 추가
- EC2에 mysql 컨테이너 실행
- dev yaml 파일 추가
- cd 변경
=> [BE] 개발 서버 도커 적용

backend/bottari/src/main/java/com/bottari/bottari/repository/BottariItemRepository.java
- 쿼리 오류 수정
- 보따리 체크 시 정상적인 보따리를 찾을 수 없던 버그 수정
<br>
- Closed #265 
<br>
문제되던 ON절(보따리아이템.id = 보따리.id)을 제거함
- 보따리 아이템 bt -> bi로 변경
- ON절 사용 대신 보따리아이템.보따리로 변경 필요 FETCH JOIN 컨벤션
<br>
최신 버전 안드로이드로 버그 수정 확인했습니다!
<br>
=> [BE] 보따리 체크 시 정상적인 보따리를 찾을 수 없던 버그 수정

backend/bottari/build.gradle, backend/bottari/src/main/java/com/bottari/support/HealthCheckMetricBinder.java, backend/bottari/src/main/resources/application-dev.yml
- 헬스 체크 API 로그 제외
<br>
- 스프링 부트 매트릭 라이브러리를 사용하여 API 호출 없이 내부적으로 헬스 체크를 한 후, 커스텀 매트릭을 Cloud Watch에게 보내도록 변경
<br>
=> [BE] 헬스 체크 API 로그 제외

backend/bottari/build.gradle, backend/bottari/src/main/java/com/bottari/support/HealthCheckMetricBinder.java, backend/bottari/src/main/resources/application-dev.yml
=> [BE] 헬스 체크 API 로그 버그 수정

android/Bottari/presentation/src/main/java/com/bottari/presentation/view/template/my/MyTemplateFragment.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/template/my/MyTemplateUiState.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/template/my/MyTemplateViewModel.kt, android/Bottari/presentation/src/main/res/layout/fragment_my_template.xml, android/Bottari/presentation/src/main/res/layout/view_my_template_empty.xml, android/Bottari/presentation/src/main/res/values/strings.xml
- 내가 등록한 보따리 화면 Empty View 구현
<br>
- Closed #297 
<br>
- 내가 등록한 보따리 화면 Empty View 구현
<br>
<br>
<br>
=> [AN] 내가 등록한 보따리 화면 Empty View 구현

backend/bottari/src/main/java/com/bottari/error/ErrorCode.java, backend/bottari/src/main/java/com/bottari/teambottari/controller/TeamBottariApiDocs.java, backend/bottari/src/main/java/com/bottari/teambottari/controller/TeamBottariController.java, backend/bottari/src/main/java/com/bottari/teambottari/domain/InviteCodeGenerator.java, backend/bottari/src/main/java/com/bottari/teambottari/domain/TeamBottari.java, backend/bottari/src/main/java/com/bottari/teambottari/dto/CreateTeamBottariRequest.java, backend/bottari/src/main/java/com/bottari/teambottari/repository/TeamBottariRepository.java, backend/bottari/src/main/java/com/bottari/teambottari/service/TeamBottariService.java, backend/bottari/src/test/java/com/bottari/teambottari/controller/TeamBottariControllerTest.java, backend/bottari/src/test/java/com/bottari/teambottari/domain/TeamBottariTest.java, backend/bottari/src/test/java/com/bottari/teambottari/domain/TeamSharedItemInfoTest.java, backend/bottari/src/test/java/com/bottari/teambottari/service/TeamBottariServiceTest.java
- 팀 보따리 생성 기능 구현
<br>
- Closed #314 
<br>
- 팀 보따리 생성 기능 구현
- 팀 보따리 생성 시 팀 멤버 데이터도 저장
- 관련 테스트 코드 작성
<br>
<br>
=> [BE] 팀 보따리 생성 기능 구현

android/Bottari/app/build.gradle.kts, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/alarm/AlarmEditViewModel.kt
- 알람 생성 실패 시 무한 로딩 문제 해결
<br>
- Closed #343 
<br>
- 로딩 상태 변경 코드 개선
<br>
=> [AN] 알람이 생성되지 않는 문제 해결

backend/bottari/src/main/java/com/bottari/teambottari/controller/TeamBottariApiDocs.java, backend/bottari/src/main/java/com/bottari/teambottari/controller/TeamBottariController.java, backend/bottari/src/main/java/com/bottari/teambottari/dto/ReadTeamBottariResponse.java, backend/bottari/src/main/java/com/bottari/teambottari/repository/TeamAssignedItemInfoRepository.java, backend/bottari/src/main/java/com/bottari/teambottari/repository/TeamAssignedItemRepository.java, backend/bottari/src/main/java/com/bottari/teambottari/repository/TeamMemberRepository.java, backend/bottari/src/main/java/com/bottari/teambottari/repository/TeamSharedItemInfoRepository.java, backend/bottari/src/main/java/com/bottari/teambottari/repository/TeamSharedItemRepository.java, backend/bottari/src/main/java/com/bottari/teambottari/service/TeamBottariService.java, backend/bottari/src/main/resources/data.sql, backend/bottari/src/test/java/com/bottari/teambottari/controller/TeamBottariControllerTest.java, backend/bottari/src/test/java/com/bottari/teambottari/service/TeamBottariServiceTest.java
- 팀 보따리 상세 조회 기능 구현
<br>
- Closed #346 
<br>
- 팀 보따리 상세 조회 기능 구현
- 편집 화면 들어가자 마자 나오는 곳에서 사용합니다.
```json
// 예시 응답
{
"id": 1,
"title": "다이스의 첫 여행 준비",
"sharedItems": [
{
"id": 1,
"name": "공용 간식"
},
{
"id": 2,
"name": "상비약"
}
],
"assignedItems": [
{
"id": 1,
"name": "항공권"
},
{
"id": 2,
"name": "크레파스"
}
],
"personalItems": [
{
"id": 1,
"name": "개인 여권"
},
{
"id": 2,
"name": "선글라스"
}
],
"alarm": null
}
```
<br>
- 목업 데이터 추가했어요.
<br>
=> [BE] 팀 보따리 상세 조회 기능 구현

android/Bottari/app/build.gradle.kts, android/Bottari/presentation/src/main/res/layout/fragment_alarm_edit.xml
- 배포를 위해 아직 구현되지 않은 위치 설정 뷰를 Gone 처리
<br>
- Closed #391 
<br>
- 배포를 위해 아직 구현되지 않은 위치 설정 뷰를 Gone 처리
<br>
<br>
=> [AN] 알람 편집 화면 위치 설정 Gone 처리 | Release v1.0.4

android/Bottari/presentation/src/main/java/com/bottari/presentation/service/fcm/ReminderMessagingService.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/checklist/personal/ChecklistActivity.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/checklist/team/TeamChecklistActivity.kt
- 뒤로가기 동작 수정
<br>
- Closed #389
<br>
- 알림을 통해 체크리스트 화면으로 접속한 경우 처리
- `onBackPressed()`가 재귀 호출되는 문제 해결
<br>
=> [AN] 팀 보따리 체크리스트 화면 뒤로가기 동작 수정

android/Bottari/app/build.gradle.kts
- Version Name:  1.0.4 -> 1.2.0
- Version Code: 7
<br>
=> [AN] 버전 업데이트 (1.0.4 -> 1.2.0)
