woowacourse-teams/2025-bottari

backend/bottari/src/main/java/com/bottari/controller/MemberController.java, backend/bottari/src/main/java/com/bottari/domain/Member.java, backend/bottari/src/main/java/com/bottari/dto/CreateMemberRequest.java, backend/bottari/src/main/java/com/bottari/repository/MemberRepository.java, backend/bottari/src/main/java/com/bottari/service/MemberService.java, backend/bottari/src/test/java/com/bottari/controller/MemberControllerTest.java, backend/bottari/src/test/java/com/bottari/domain/MemberTest.java, backend/bottari/src/test/java/com/bottari/service/MemberServiceTest.java
- 사용자 등록 기능 구현 및 검증
<br>
Closed #1 
<br>
- `Member` 도메인 추가 및 사용자 이름 검증
- `Member` 관련 controller, service, repository 추가
<br>
- 4인 페어 진행
<br>
=> [BE] 사용자 등록 기능 구현

backend/bottari/src/main/java/com/bottari/controller/AlarmController.java, backend/bottari/src/main/java/com/bottari/domain/Alarm.java, backend/bottari/src/main/java/com/bottari/dto/CreateAlarmRequest.java, backend/bottari/src/main/java/com/bottari/dto/UpdateAlarmRequest.java, backend/bottari/src/main/java/com/bottari/service/AlarmService.java, backend/bottari/src/test/java/com/bottari/controller/AlarmControllerTest.java, backend/bottari/src/test/java/com/bottari/domain/AlarmTest.java, backend/bottari/src/test/java/com/bottari/service/AlarmServiceTest.java
- 알람 생성 기능 구현
- 알람 수정 기능 구현
<br>
- Closed #44 
<br>
- 알람 생성 및 수정 기능 구현
- 알람 생성 및 수정 기능 테스트 작성
<br>
- 2인 페어 진행
- 알람 on/off API 구현 필요 @unh6unh6 
- 알람을 아직 생성하지 않았다면, 알람 활성화 버튼(`isActive`)를 누를 수 없다.
- 알람을 생성한 이후에는 isActive 토글 버튼을 누를 수 있다.
- 따라서 알람 추가 및 수정 시에는 알람의 isActive 필드를 저장하지 않고, 별도로 API를 추가해야 한다.
- <안드로이드 팀원과 협의된 내용>
<br>
=> [BE] 알람 생성 및 수정 기능 구현

backend/bottari/src/main/java/com/bottari/controller/BottariItemController.java, backend/bottari/src/main/java/com/bottari/dto/EditBottariItemsRequest.java, backend/bottari/src/main/java/com/bottari/repository/BottariItemRepository.java, backend/bottari/src/main/java/com/bottari/service/BottariItemService.java, backend/bottari/src/test/java/com/bottari/controller/BottariItemControllerTest.java, backend/bottari/src/test/java/com/bottari/service/BottariItemServiceTest.java
- 보따리 물품 일괄 추가 및 삭제 기능 구현
<br>
- Closed #45 
<br>
- 보따리 물품 일괄 추가 및 삭제 기능 구현
- 보따리가 존재하지 않는 경우 검증
- 삭제하려는 물품이 특정 보따리 내에 존재하지 않는 경우 검증
- 추가하려는 물품명에 중복이 존재하는 경우 검증 (요청 내)
- 추가하려는 물품명이 이미 DB에 존재하는 경우 검증
- 보따리 수정 API 대응
- PATCH /bottaries/{bottariId}/bottari-items
요청 내의 delete_id 리스트 내에 중복이 존재하는 경우,
이를 올바르지 않은 요청으로 처리하여 예외를 던질지, 서버 내에서 중복을 제거하고 삭제할지
논의 필요
- 현재 중복을 제거하지 않고, 올바르지 않은 요청으로 처리하여 예외를 던지는 중
<br>
- 페어프로그래밍 with 코기 / 훌라
<br>
=> [BE] 보따리 물품 일괄 추가 및 삭제 기능 구현

backend/bottari/src/main/java/com/bottari/controller/BottariTemplateController.java, backend/bottari/src/main/java/com/bottari/controller/docs/BottariTemplateApiDocs.java, backend/bottari/src/main/java/com/bottari/repository/BottariTemplateItemRepository.java, backend/bottari/src/main/java/com/bottari/service/BottariTemplateService.java, backend/bottari/src/test/java/com/bottari/controller/BottariTemplateControllerTest.java, backend/bottari/src/test/java/com/bottari/service/BottariTemplateServiceTest.java
- 보따리 템플릿으로 보따리를 생성하는 기능 구현
<br>
- Closed #64 
<br>
- 보따리 템플릿으로 보따리 생성 기능 추가
- 보따리 템플릿으로 보따리 생성 API 추가
- 보따리 템플릿으로 보따리 생성 기능 및 예외 발생 로직 검증
<br>
- 기존에 사용하기로 한 URL
```
/templates/{id}/import
```
- 현재 구현한 URL
```
/templates/{id}/create-bottari
```
`BottariTemplateController`에서 처리하는 작업인데 import(불러온다)라는 말이 어색하다고 느껴서 아래와 같이 구현함.
또한 import로 네이밍을 할 시, 어떤 행위를 하는지 모호하다고 생각됨.
이건 어떤지 ... 🤔
<br>
=> [BE] 보따리 템플릿으로 보따리를 생성하는 기능 구현

backend/bottari/src/main/java/com/bottari/controller/MemberController.java, backend/bottari/src/main/java/com/bottari/controller/docs/MemberApiDocs.java, backend/bottari/src/main/java/com/bottari/dto/CheckRegistrationResponse.java, backend/bottari/src/main/java/com/bottari/service/MemberService.java, backend/bottari/src/test/java/com/bottari/controller/MemberControllerTest.java, backend/bottari/src/test/java/com/bottari/service/MemberServiceTest.java
- SSAID로 회원가입 여부 및 사용자 이름 조회 기능 구현
<br>
- Closed #74
<br>
- SSAID로 회원가입 여부 및 사용자 이름 조회 기능 구현
- 가입된 SSAID 일 시, true / name
- 미가입된 SSAID 일 시, false / null
<br>
- 벨로 호떡 2인 페어 진행
=> [BE] SSAID로 회원가입 여부 및 사용자 이름 조회 기능 구현

android/Bottari/presentation/src/main/AndroidManifest.xml, android/Bottari/presentation/src/main/java/com/bottari/presentation/util/permission/PermissionUtil.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/personal/main/PersonalBottariEditFragment.kt, android/Bottari/presentation/src/main/res/values/strings.xml
- 권한 관리 클래스 PermissionUtil 구현
<br>
- Closed #50 
<br>
- 권한 관리 로직을 담당하는 PermissionUtil 구현
- 위치 권한 추가 (`ACCESS_COARSE_LOCATION`, `ACCESS_FINE_LOCATION`)
- 알람 권한 추가 (`SCHEDULE_EXACT_ALARM`, `POST_NOTIFICATIONS`)
1. 알람 클릭 시 위치 및 알람 권한 요청 (모든 권한 허용 시 알람 편집 화면으로 이동)
2. 권한 거절 시 스낵바 출력
3. 권한 요청 2회 이상 실패할 경우 설정 화면 이동 여부를 묻는 다이얼로그 출력
4. 영구적으로 권한 거절 시 알람 편집 화면으로 이동하지 않음
<br>
| 권한 요청 | 권한 거절 | 설정 이동 (런타임 권한) | 설정 이동 (특별 권한) |
|--------|-------|-------|-------|
| <img width="160" height="356" alt="image" src="https://github.com/user-attachments/assets/de8f46cc-d0f6-4ed4-8640-94cba5e4c48b" />| <img width="160" height="356" alt="image" src="https://github.com/user-attachments/assets/35c1b98b-e67d-4818-b73f-e69b908c638e" /> | <img width="160" height="356" alt="image" …
=> [AN] PermissionUtil 구현

backend/bottari/src/main/java/com/bottari/GlobalExceptionHandler.java
- 전역 예외 핸들링 추가하고 및 예외 응답을 하도록 한다.
<br>
- Closed #72 
<br>
- `@ControllerAdvice`와 `@ExceptionHandler` 전역 예외를 핸들링 하도록 구현
- 전역 예외 핸들러에서 예외 메시지를 담은 ProblemDetails를 응답하도록 구현
- 에러를 핸들링하여 stack trace가 콘솔 로그에 안뜨므로, 예외 상황을 간단한 로깅하는 기능 구현
<br>
- 호떡, 코기, 벨로 3인 페어 진행
<br>
=> [BE] 전역 예외 핸들링 추가 및 예외 응답 구현

android/Bottari/data/src/main/java/com/bottari/data/model/item/SaveBottariItemsRequest.kt, android/Bottari/data/src/main/java/com/bottari/data/repository/BottariItemRepositoryImpl.kt, android/Bottari/data/src/main/java/com/bottari/data/service/BottariItemService.kt, android/Bottari/data/src/main/java/com/bottari/data/service/BottariService.kt, android/Bottari/data/src/main/java/com/bottari/data/source/remote/BottariItemRemoteDataSource.kt, android/Bottari/data/src/main/java/com/bottari/data/source/remote/BottariItemRemoteDataSourceImpl.kt, android/Bottari/di/src/main/java/com/bottari/di/UseCaseProvider.kt, android/Bottari/domain/src/main/java/com/bottari/domain/repository/BottariItemRepository.kt, android/Bottari/domain/src/main/java/com/bottari/domain/usecase/item/SaveBottariItemsUseCase.kt, android/Bottari/presentation/build.gradle.kts, android/Bottari/presentation/src/main/java/com/bottari/presentation/extension/ParcelableExtension.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/model/AlarmUiModel.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/model/BottariDetailUiModel.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/model/BottariItemUiModel.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/model/DayOfWeekUiModel.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/model/LocationAlarmUiModel.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/personal/item/PersonalItemEditFragment.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/personal/item/PersonalItemEditViewModel.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/personal/main/PersonalBottariEditFragment.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/personal/main/PersonalBottariEditViewModel.kt
- 개인 보따리 물건 편집 화면 API 연동 작업
<br>
- Closed #96
<br>
```kotlin
{
"deleteItemIds": [
0
],
"createItemNames": [
"string"
]
}
```
서버에서의 체크리스트 상태를 유지하기 위해
삭제 물품과 기존에 없던 새로운 상품으로 구분하여 요청을 진행
<br>
<br>
=> [AN] 개인 보따리 물건 편집 화면 API 연동

android/Bottari/app/src/main/java/com/bottari/bottari/view/MainActivity.kt, android/Bottari/app/src/main/java/com/bottari/bottari/view/MainViewModel.kt, android/Bottari/data/src/main/java/com/bottari/data/mapper/MemberMapper.kt, android/Bottari/data/src/main/java/com/bottari/data/model/member/CheckRegisteredMemberResponse.kt, android/Bottari/data/src/main/java/com/bottari/data/repository/MemberRepositoryImpl.kt, android/Bottari/data/src/main/java/com/bottari/data/service/MemberService.kt, android/Bottari/data/src/main/java/com/bottari/data/source/remote/MemberRemoteDataSource.kt, android/Bottari/data/src/main/java/com/bottari/data/source/remote/MemberRemoteDataSourceImpl.kt, android/Bottari/di/src/main/java/com/bottari/di/UseCaseProvider.kt, android/Bottari/domain/src/main/java/com/bottari/domain/model/member/RegisteredMember.kt, android/Bottari/domain/src/main/java/com/bottari/domain/repository/MemberRepository.kt, android/Bottari/domain/src/main/java/com/bottari/domain/usecase/member/CheckRegisteredMemberUseCase.kt
- 사용자 조회 API 연동
<br>
- Closed #118 
<br>
- 사용자 회원 가입 여부를 체크 후 `사용자 등록` / `홈 화면 진입` 분기 처리
<br>
<br>
=> [AN] 사용자 조회 API 연동

backend/bottari/src/main/java/com/bottari/controller/MemberController.java, backend/bottari/src/main/java/com/bottari/controller/docs/MemberApiDocs.java, backend/bottari/src/main/java/com/bottari/domain/Member.java, backend/bottari/src/main/java/com/bottari/dto/UpdateMemberRequest.java, backend/bottari/src/main/java/com/bottari/repository/MemberRepository.java, backend/bottari/src/main/java/com/bottari/service/MemberService.java, backend/bottari/src/test/java/com/bottari/controller/MemberControllerTest.java, backend/bottari/src/test/java/com/bottari/domain/MemberTest.java, backend/bottari/src/test/java/com/bottari/service/MemberServiceTest.java
- 사용자 이름을 수정하는 API를 구현합니다.
<br>
- Closed #143
<br>
- 사용자 이름을 수정하는 API 구현
- 이미 사용하는 이름으로 수정할 경우 예외 발생
- 현재 이름과 똑같은 이름인 경우 예외 발생 (따라서 같은 이름으로 수정할 경우 안드로이드에서 API 호출 X)
- 사용자 이름 엔티티에 유니크 제약 조건 추가
- 추후 마켓 플레이스에 보따리 템플릿 공유자 이름을 보여주기 위함 (식별성)
<br>
<br>
=> [BE] 사용자 이름 변경 기능 구현

backend/bottari/src/main/java/com/bottari/controller/BottariController.java, backend/bottari/src/main/java/com/bottari/controller/docs/BottariApiDocs.java, backend/bottari/src/main/java/com/bottari/repository/AlarmRepository.java, backend/bottari/src/main/java/com/bottari/repository/BottariItemRepository.java, backend/bottari/src/main/java/com/bottari/repository/BottariRepository.java, backend/bottari/src/main/java/com/bottari/service/BottariService.java, backend/bottari/src/test/java/com/bottari/controller/BottariControllerTest.java, backend/bottari/src/test/java/com/bottari/service/BottariServiceTest.java
- 보따리 삭제 기능
<br>
- Closed #141 
<br>
- 보따리 삭제 기능 구현
- 본인 보따리만 삭제 가능하도록 검증
```java
@Transactional
public void deleteById(
final Long id,
final String ssaid
) {
final Bottari bottari = bottariRepository.findById(id)
.orElseThrow(() -> new IllegalArgumentException("보따리를 찾을 수 없습니다."));
validateOwner(ssaid, bottari);
bottariItemRepository.deleteByBottariId(id);
alarmRepository.deleteByBottariId(id);
bottariRepository.deleteById(id);
}
```
`cascade` 설정을 통해 삭제를 하려고 했으나, 그 경우 delete 쿼리가 item의 갯수 만큼 실행됨
```java
@Modifying
@Query("DELETE FROM BottariItem bt WHERE bt.bottari.id = :bottariId")
void deleteByBottariId(Long bottariId);
```
기존의 `deleteByBottariId` 또한 select 쿼리 이후, item 갯수 만큼 delete 쿼리가 실행되므로 직접 쿼리 작성
<br>
<br>
=> [BE] 보따리 삭제 기능

backend/bottari/build.gradle, backend/bottari/src/main/java/com/bottari/config/RetryConfig.java, backend/bottari/src/main/java/com/bottari/dto/CreateMemberRequest.java, backend/bottari/src/main/java/com/bottari/service/MemberService.java, backend/bottari/src/test/java/com/bottari/controller/MemberControllerTest.java, backend/bottari/src/test/java/com/bottari/service/MemberServiceTest.java
- 사용자 등록 시 사용자 이름을 받던 방식에서 서버에서 무작위로 생성하는 방식으로 변경
<br>
- Closed #157 
<br>
- 고유한 닉네임을 생성하는 과정이 어렵지 않기 때문에 별도 락이 아닌 재시도 방식으로 구현
`create()` 메서드는 회원 생성 시 랜덤한 임시 이름을 부여하고 저장하는 로직입니다.
- 사용자 이름(name)에는 `유니크 제약조건`이 설정되어 있어 중복 발생 시 `DataIntegrityViolationException`이 발생할 수 있으며, 이를 최대 `3회`까지 재시도합니다.
- `@Retryable`의 maxAttempts 속성은 기본값이 3이지만, 명확히 나타내기 위해 작성했습니다.
- 재시도는 지수 백오프(exponential backoff) 정책을 적용했습니다. `300ms → 600ms → 1200ms`
- 모든 재시도 실패 시, `@Recover` 메서드가 호출되어 사용자에게 구체적인 예외 메시지를 전달합니다.
- `@Recover`를 적용한 메서드에는 예외 타입과 예외가 발생한 메서드의 기본 파라미터를 받아야 합니다.
> ⚠️ 주의
> 
> `@Retryable`은 Spring AOP 기반으로 동작하므로,
> 같은 클래스 내부에서 호출되면 retry가 적용되지 않습니다.
> 따라서 외부에서 직접 호출되는 구조로 유지했습니다.
<br>
- 가입 시 받는 임시 이름 형태
<br>
<br>
=> [BE] 사용자 등록 흐름 변경

.github/workflows/android-ci.yaml, android/Bottari/app/build.gradle.kts, android/Bottari/app/proguard-rules.pro, android/Bottari/build.gradle.kts, android/Bottari/data/src/main/java/com/bottari/data/local/UserInfoDataStore.kt, android/Bottari/data/src/main/java/com/bottari/data/mapper/MemberMapper.kt, android/Bottari/data/src/main/java/com/bottari/data/model/member/CheckRegisteredMemberResponse.kt, android/Bottari/data/src/main/java/com/bottari/data/repository/MemberRepositoryImpl.kt, android/Bottari/data/src/main/java/com/bottari/data/source/local/UserInfoLocalDataSource.kt, android/Bottari/data/src/main/java/com/bottari/data/source/local/UserInfoLocalDataSourceImpl.kt, android/Bottari/data/src/main/java/com/bottari/data/source/remote/MemberRemoteDataSource.kt, android/Bottari/data/src/main/java/com/bottari/data/source/remote/MemberRemoteDataSourceImpl.kt, android/Bottari/data/src/test/java/com/bottari/data/repository/MemberRepositoryImplTest.kt, android/Bottari/di/src/main/java/com/bottari/di/DataSourceProvider.kt, android/Bottari/di/src/main/java/com/bottari/di/DataStoreProvider.kt, android/Bottari/di/src/main/java/com/bottari/di/RepositoryProvider.kt, android/Bottari/domain/src/main/java/com/bottari/domain/model/member/RegisteredMember.kt, android/Bottari/domain/src/main/java/com/bottari/domain/repository/MemberRepository.kt, android/Bottari/domain/src/main/java/com/bottari/domain/usecase/member/RegisterMemberUseCase.kt, android/Bottari/gradle/libs.versions.toml, android/Bottari/presentation/build.gradle.kts, android/Bottari/presentation/src/main/java/com/bottari/presentation/common/base/BaseActivity.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/common/base/BaseFragment.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/util/CrashlyticsLogger.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/main/MainViewModel.kt
- Firebase Crashlytics 설정
<br>
- Closed #181 
<br>
- Firebase 의존성 설정
- Firebase Crashlytics 설정
- 디스코드 웹훅 플로우 구축
- `CrashlyticsLogger` 구현
- ProGuard 설정
<br>
[보따리 - 외부 모니터링 도구 Wiki](https://github.com/woowacourse-teams/2025-bottari/wiki/%5BAN%5D-외부-모니터링-도구-연동)
<br>
=> [AN] Firebase Crashlytics 설정

backend/bottari/src/main/java/com/bottari/bottari/controller/BottariItemApiDocs.java, backend/bottari/src/main/java/com/bottari/bottari/controller/BottariItemController.java, backend/bottari/src/main/java/com/bottari/bottari/domain/BottariItem.java, backend/bottari/src/main/java/com/bottari/bottari/repository/BottariItemRepository.java, backend/bottari/src/main/java/com/bottari/bottari/service/BottariItemService.java, backend/bottari/src/main/java/com/bottari/error/ErrorCode.java, backend/bottari/src/test/java/com/bottari/bottari/controller/BottariItemControllerTest.java, backend/bottari/src/test/java/com/bottari/bottari/domain/BottariItemTest.java, backend/bottari/src/test/java/com/bottari/bottari/service/BottariItemServiceTest.java
- 개인 보따리 체크 시, 본인 확인 로직 구현
<br>
- Closed #251 
<br>
- 개인 보따리 체크 / 언체크 시, 본인 확인 로직 구현
- `BottariItem` 조회 시, `Bottari` fetch join
- `Bottari` 내의 `isOwner` 메서드 재사용
- 에러코드 추가 `BOTTARI_ITEM_NOT_OWNED(HttpStatus.FORBIDDEN, "해당 보따리 물품에 접근할 수 있는 권한이 없습니다.")`
<br>
<br>
=> [BE] 개인 보따리 체크 시, 본인 확인

backend/bottari/src/main/java/com/bottari/error/ErrorCode.java, backend/bottari/src/main/java/com/bottari/teambottari/domain/TeamAssignedItem.java, backend/bottari/src/main/java/com/bottari/teambottari/domain/TeamAssignedItemInfo.java, backend/bottari/src/main/java/com/bottari/teambottari/domain/TeamBottari.java, backend/bottari/src/main/java/com/bottari/teambottari/domain/TeamMember.java, backend/bottari/src/main/java/com/bottari/teambottari/domain/TeamPersonalItem.java, backend/bottari/src/main/java/com/bottari/teambottari/domain/TeamSharedItem.java, backend/bottari/src/main/java/com/bottari/teambottari/domain/TeamSharedItemInfo.java, backend/bottari/src/test/java/com/bottari/fixture/TeamBottariFixture.java, backend/bottari/src/test/java/com/bottari/teambottari/domain/TeamAssignedItemInfoTest.java, backend/bottari/src/test/java/com/bottari/teambottari/domain/TeamBottariTest.java, backend/bottari/src/test/java/com/bottari/teambottari/domain/TeamPersonalItemTest.java, backend/bottari/src/test/java/com/bottari/teambottari/domain/TeamSharedItemInfoTest.java
- 팀 보따리 관련 엔티티 설계
<br>
- Closed #229 
<br>
- 팀 보따리 관련 엔티티 구현
- 해당 엔티티 기본 검증 로직 구현
- 해당 기본 검증 로직 테스트 추가
<br>
<br>
- 추가적인 도메인 로직은 기능 구현하면서 추가하는게 나을 것 같음 (예 : check, uncheck ..)
- 현재 `TeamBottari`과 `Alarm`간 의존관계 없음
- 차후 `Bottari`가 `Alarm`의 외래키를 가지고 있도록 수정 한 후, 이부분도 수정해야 할듯 ? 
<br>
=> [BE] 팀 보따리 관련 엔티티 설계

android/Bottari/presentation/src/main/java/com/bottari/presentation/receiver/AlarmReceiver.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/util/AlarmScheduler.kt
- 각 보따리 별 알람의 고유 식별자 통일
<br>
- Closed #268
<br>
- 보따리 알람 설정 시 알람 유형과 상관없이 하나의 식별자를 사용하도록 개선
- `AlarmReceiver`에서 다음 알람을 설정하는 메소드 호출
<br>
- 일회성 알람을 설정할 때 현재 날짜의 이전 시간을 선택할 경우 바로 알람이 울리는 문제가 있었는데, 우선은 알람 자체가 설정되지 않도록 했습니다. 알람 편집 화면에서 해결할 수 있을 것 같은데 이에 대한 논의가 필요합니다.
<br>
=> [AN] 알람 ID를 식별하지 못하는 문제

backend/bottari/src/main/java/com/bottari/teambottari/controller/TeamBottariApiDocs.java, backend/bottari/src/main/java/com/bottari/teambottari/controller/TeamBottariController.java, backend/bottari/src/main/java/com/bottari/teambottari/controller/TeamMemberApiDocs.java, backend/bottari/src/main/java/com/bottari/teambottari/dto/ReadTeamBottariPreviewResponse.java, backend/bottari/src/main/java/com/bottari/teambottari/dto/TeamBottariMemberCountProjection.java, backend/bottari/src/main/java/com/bottari/teambottari/repository/TeamAssignedItemRepository.java, backend/bottari/src/main/java/com/bottari/teambottari/repository/TeamMemberRepository.java, backend/bottari/src/main/java/com/bottari/teambottari/repository/TeamPersonalItemRepository.java, backend/bottari/src/main/java/com/bottari/teambottari/repository/TeamSharedItemRepository.java, backend/bottari/src/main/java/com/bottari/teambottari/repository/dto/TeamBottariMemberCountProjection.java, backend/bottari/src/main/java/com/bottari/teambottari/service/TeamBottariService.java, backend/bottari/src/test/java/com/bottari/teambottari/controller/TeamBottariControllerTest.java, backend/bottari/src/test/java/com/bottari/teambottari/service/TeamBottariServiceTest.java
- 팀 보따리 조회 기능 구현
<br>
- Closed #324 
<br>
- 내가 속한 팀 보따리 목록 조회 기능
- 개인 보따리랑 팀 보따리 화면을 분리함 [다이스 PR](https://github.com/woowacourse-teams/2025-bottari/pull/332) 화면 이미지 참고
<br>
- 알람은 아직 미구현 상태입니다. (알람, 엔티티 매핑 방향 논의 필요)
<br>
=> [BE] 내 팀 보따리 목록 조회 기능 구현

backend/bottari/src/main/java/com/bottari/teambottari/repository/TeamSharedItemRepository.java, backend/bottari/src/test/java/com/bottari/teambottari/service/TeamItemFacadeTest.java
- 충돌로 생긴 중복된 메서드 지워서 해결
<br>
- 긴급 수정
<br>
- 통과함 
<br>
<br>
=> [BE] 중복된 메서드 제거로 충돌 해결

.github/workflows/android-ci.yaml
- CI 워크플로우 캐싱 도입으로 속도 개선
<br>
- 없습니다.
<br>
> ### 요약
>
> CI 파이프라인의 무료 사용량(혹은 자원) 절감을 위해 캐싱 전략을 도입하여 빌드(Andorid CI Workflow) 시간을 단축
무료 Organization의 무료 러닝 타임은 2,000분/1달로 알고 있는데, 
2주만에 약 67%를 소모했고,
그중에서 Android CI가 49%를 차지합니다.
- [GitHub 공식 요금 표](https://docs.github.com/en/billing/concepts/product-billing/github-actions#included-storage-and-minutes)에서 GitHub Free for organizations 부분 참고
간단한 작업이라 바로 PR로 올렸습니다.
직접 핏하게 수정하고 반영하셔도 돼요.
| 항목       | 이전 방식 (비효율적)                        | 개선된 방식 (효율적)                                  |
| ---------- | ------------------------------------------- | ---------------------------------------------------- |
| 실행 제어  | 새 커밋마다 계속 새롭게 실행                 | 최신 커밋만 실행, 이전 작업은 자동 취소 (`concurrency`) |
| 코드 다운로드 | 프로젝트 전체 이력 다운로드                 | 최신 코드만 다운로드 …
=> [AN] CI 워크플로우 캐싱 도입으로 속도 개선

android/Bottari/data/src/main/java/com/bottari/data/model/member/RegisterMemberRequest.kt, android/Bottari/data/src/main/java/com/bottari/data/repository/MemberRepositoryImpl.kt, android/Bottari/data/src/test/java/com/bottari/data/repository/MemberRepositoryImplTest.kt, android/Bottari/domain/src/main/java/com/bottari/domain/repository/MemberRepository.kt, android/Bottari/domain/src/main/java/com/bottari/domain/usecase/member/RegisterMemberUseCase.kt, android/Bottari/gradle/libs.versions.toml, android/Bottari/presentation/build.gradle.kts, android/Bottari/presentation/src/main/AndroidManifest.xml, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/main/MainViewModel.kt
- 사용자 등록 시 FCM 토큰 전달
<br>
- Closed #370
<br>
- 사용자 등록 시 FCM 토큰 전달
<br>
<br>
=> [AN] 사용자 등록 시 FCM 토큰 전달

backend/bottari/src/main/java/com/bottari/error/ErrorCode.java, backend/bottari/src/main/java/com/bottari/teambottari/controller/TeamMemberApiDocs.java, backend/bottari/src/main/java/com/bottari/teambottari/controller/TeamMemberController.java, backend/bottari/src/main/java/com/bottari/teambottari/dto/JoinTeamBottariRequest.java, backend/bottari/src/main/java/com/bottari/teambottari/repository/TeamBottariRepository.java, backend/bottari/src/main/java/com/bottari/teambottari/repository/TeamMemberRepository.java, backend/bottari/src/main/java/com/bottari/teambottari/service/TeamMemberService.java, backend/bottari/src/test/java/com/bottari/teambottari/controller/TeamMemberControllerTest.java, backend/bottari/src/test/java/com/bottari/teambottari/service/TeamMemberServiceTest.java
- 초대 코드와 ssaid를 통해 팀 보따리에 참여하는 API
<br>
- Closed #349 
<br>
- 비즈니스 로직 수행 순서
1. 초대코드에 해당하는 팀 보따리 존재 여부 확인
2. 멤버 존재 여부 확인
3. 해당 멤버 팀 보따리 미소속 확인
4. 해당 멤버를 팀 보따리의 팀 멤버로 추가
5. 팀 보따리 공통 물건을 해당 팀 멤버에게 추가
<br>
<br>
=> [BE] 팀 보따리 초대 코드로 팀 보따리 참여 기능 구현

backend/bottari/src/main/java/com/bottari/bottari/domain/Bottari.java, backend/bottari/src/main/java/com/bottari/error/ErrorCode.java, backend/bottari/src/main/java/com/bottari/fcm/FcmMessageConverter.java, backend/bottari/src/main/java/com/bottari/fcm/dto/MessageType.java, backend/bottari/src/main/java/com/bottari/member/domain/Member.java, backend/bottari/src/main/java/com/bottari/teambottari/controller/TeamMemberApiDocs.java, backend/bottari/src/main/java/com/bottari/teambottari/controller/TeamMemberController.java, backend/bottari/src/main/java/com/bottari/teambottari/dto/ReadTeamMemberStatusResponse.java, backend/bottari/src/main/java/com/bottari/teambottari/repository/TeamMemberRepository.java, backend/bottari/src/main/java/com/bottari/teambottari/service/TeamMemberService.java, backend/bottari/src/test/java/com/bottari/teambottari/controller/TeamMemberControllerTest.java, backend/bottari/src/test/java/com/bottari/teambottari/service/TeamMemberServiceTest.java
- 팀 보따리 멤버 별 보채기 기능 구현
<br>
- Closed #376 
<br>
1. 보채기를 보내는 Member 조회 및 없으면 예외
2. 보채기를 받는 Member 조회 및 없으면 예외
3. 보내는 사람과 받는 사람이 동일하다면 예외
4. TeamBottari 조회 및 없으면 예외
5. 보내는 사람이 팀 보따리 소속인지 확인 후 아니라면 예외
6. 받는 사람이 팀 보따리 소속인지 확인 후 아니라면 예외
7. 받는 사람의 공통 아이템 중 체크하지 않은 아이템 조회
8. 받는 사람의 담당 아이템 중 체크하지 않은 아이템 조회
9. 모든 공통/담당 아이템을 체크했다면 예외
10. FCM 메시지 전송
<br>
- FCM 응답 json 메시지 예시는 아래와 같음
```json
{
"data": {
"teamBottariId": "1",
"teamBottariTitle": "주말 캠핑 준비",
"teamSharedItemNames": "[\"텐트\",\"버너\"]",
"teamAssignedItemNames": "[\"물\",\"고기\"]"
},
"messageType": "REMIND_BY_TEAM_MEMBER"
}
```
- FCM message에 `Map<String, String>`만 넣을 수 있어서 value에 List 반환을 못함
- 안드로이드에서 item names 파싱 로직이 필요할 듯
- 코드리뷰하러 checkout을 자주하다보니 temp 커밋을 실수로 안되돌렸음..
- 어짜피 스쿼시 되니깐 괜찮을거예요 ~
<br>
=> [BE] 팀 보따리 멤버 별 보채기 기능 구현

android/Bottari/data/src/main/java/com/bottari/data/repository/MemberRepositoryImpl.kt, android/Bottari/data/src/main/java/com/bottari/data/source/local/MemberIdentifierLocalDataSourceImpl.kt, android/Bottari/data/src/test/java/com/bottari/data/repository/MemberRepositoryImplTest.kt, android/Bottari/di/src/main/java/com/bottari/di/UseCaseProvider.kt, android/Bottari/domain/src/main/java/com/bottari/domain/repository/MemberRepository.kt, android/Bottari/domain/src/main/java/com/bottari/domain/usecase/member/GetMemberIdentifierUseCase.kt
- 사용자 식별자 조회 기능 구현
<br>
- Closed #399 
<br>
`GetMemberIndenifierUseCase()`로 사용자 식별자를 조회하는 기능을 구현했습니다.
<br>
<br>
=> [AN] 사용자 식별자 조회 기능 구현

android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/team/item/personal/TeamPersonalItemEditFragment.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/team/item/shared/TeamSharedItemEditEvent.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/team/item/shared/TeamSharedItemEditFragment.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/team/item/shared/TeamSharedItemEditUiState.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/team/item/shared/TeamSharedItemEditViewModel.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/team/item/shared/adapter/TeamSharedItemEditAdapter.kt, android/Bottari/presentation/src/main/java/com/bottari/presentation/view/edit/team/item/shared/adapter/TeamSharedItemEditViewHolder.kt, android/Bottari/presentation/src/main/res/layout/fragment_team_shared_item_edit.xml
- 팀 공유 물품 수정 화면을 구현
<br>
- Closed #368 
<br>
- 팀 공유 물품 수정 화면을 구현
- 현재 보고 있는 타입에서만 중복 체크를 진행하도록 수정
<br>
[Screen_recording_20250817_212139.webm](https://github.com/user-attachments/assets/49b995e9-5bd6-4b39-8081-f8e12f315cb5)
<br>
=> [AN] 팀 보따리 공통 물품 수정 화면 구현
